spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:./appdb
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true